name: GPatch_env
channels:
  - broad-viral
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - biopython=1.84=py312h9a8786e_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - editdistance=0.6.2=py312h30efb56_2
  - gpatch=0.3.5=pyhdfd78af_0
  - k8=1.2=h6618dc6_3
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libblas=3.9.0=26_linux64_openblas
  - libcblas=3.9.0=26_linux64_openblas
  - libcurl=8.11.1=h332b0f4_0
  - libdeflate=1.23=h4ddbbb0_0
  - libedit=3.1.20240808=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - liblapack=3.9.0=26_linux64_openblas
  - liblzma=5.6.3=hb9d3cd8_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libsqlite=3.47.2=hee588c1_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - minimap2=2.28=h577a1d6_4
  - ncurses=6.5=he02047a_1
  - numpy=2.2.1=py312h7e784f5_0
  - openssl=3.4.0=h7b32b05_1
  - pip=24.3.1=pyh8b19718_2
  - pysam=0.22.1=py312h47d5410_3
  - python=3.12.8=h9e4cc4f_1_cpython
  - python_abi=3.12=5_cp312
  - readline=8.2=h8228510_1
  - setuptools=75.6.0=pyhff2d567_1
  - sysroot_linux-64=2.17=h57e8cba_10
  - textdistance=4.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2024b=hc8b5060_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
    - edlib==1.3.9.post1
prefix: /data/software/Anaconda3/2022.10/envs/GPatch_env
